name: Lean's OpenWrt Nano Sdk

on: 
  workflow_dispatch:
  watch:
    types: started
    
env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  CONFIG_FILE: gdock128.config
  DIY_P1_SH: sdk.sh
  DIY_P2_SH: mod.sh

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get update
        sudo -E apt-get install libtool-bin gperf python-docutils autopoint gettext
        sudo timedatectl set-timezone "Asia/Shanghai"
        
    - name: Clone source code
      run: |
        git clone $REPO_URL -b $REPO_BRANCH openwrt
               
    - name: Update feeds
      run: cd openwrt && ./scripts/feeds update -a

    - name: Install feeds
      run: cd openwrt && ./scripts/feeds install -a
        
    - name: Load Prepare toolchain
      run: |
        cd openwrt
        curl -O -L https://github.com/qpzr/SDK/releases/download/v5.4/sdk.tar.xz
        mkdir -p sdk
        tar -xJf sdk.tar.xz -C sdk
        cp -rf sdk/*/staging_dir/* ./staging_dir/
        rm -rf sdk.tar.xz sdk
        sed -i '/\(tools\|toolchain\)\/Makefile/d' Makefile
        ln -sf /usr/bin/python staging_dir/host/bin/python
        ln -sf /usr/bin/python staging_dir/host/bin/python3
        
    - name: Load custom configuration
      run: |
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
        chmod +x $DIY_P2_SH
        cd openwrt
        $GITHUB_WORKSPACE/$DIY_P2_SH
    - name: Download package
      id: package
      run: |
        cd openwrt
        make defconfig
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;
        
    - name: Compile the firmware
      id: compile
      run: |
        cd openwrt
        echo -e "$(($(nproc)+1)) thread compile"
        make -j$(($(nproc)+1)) || make -j1 || make -j1 V=s
        
    - name: Push  空投回国
      run: |
        cd openwrt/bin
        git init
        git config user.name "一支穿云箭"
        git config user.email "action@github.com"
        git add .
        git commit -m "$(date "+%Y-%m-%d %H:%M")~千军万马来相见！" -a
        ${{ secrets.SDK}}
 
    - name: Delete workflow runs
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 3
